version: '3.8'
services:
  # app:
  #   build: .
  #   ports:
  #     - '3001:3001'
  #   depends_on:
  #     - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: graphql_trial_db
      MYSQL_USER: user-graphql-trial
      MYSQL_PASSWORD: P_ssw0rd
      MYSQL_ROOT_PASSWORD: P_ssw0rd
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql1
      - ./init-db:/docker-entrypoint-initdb.d
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '13306:3306'
    restart: always

volumes:
  db_data:
